; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = mega2560, esp32


[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

build_flags =
    -D TARGET_MEGA2560

build_src_filter =
    +<**/*.c>
    +<**/*.cpp>
    -<platform/esp32/**> ; ignore all files of esp32 for mega2560 build


[env:esp32]
platform = espressif32 ;https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino

build_flags =
    -D TARGET_ESP32

build_src_filter =
    +<**/*.c>
    +<**/*.cpp>
    -<platform/mega/**> ; ignore all files of mega for esp32 build
